name: app_cinema_full
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^6.0.9
  intl: ^0.18.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.1.1
  isar_generator: ^3.0.5
  analyzer: 5.13.0

flutter:
  uses-material-design: true
  assets:
  - .env
